# Spring properties
spring:
  application:
    name: PortalCommonApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta

# HTTP Server
server:
  port: ${PORT:2223}   # HTTP (Tomcat) port

management:  # If you set off security...
  security:
    enabled: false

datasource:
  cc:
    driver-class-name: <PAAS-TA_DB_DRIVER>                                         # (e.g. org.postgresql.Driver OR com.mysql.jdbc.Driver)
    url: jdbc:<PAAS-TA_DATABASE>://<PAAS-TA_DB_IP>:<PAAS-TA_DB_PORT>/<CC_DB_NAME>  # (e.g. PAAS-TA_DATABASE :: postgresql OR mysql)
    username: <CC_DB_USER_NAME>
    password: <CC_DB_USER_PASSWORD>
  portal:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://<PORTAL_DB_IP>:<PORTAL_DB_PORT>/portaldb
    username: <PORTAL_DB_USER>
    password: <PORTAL_DB_USER_PASSWORD>
  uaa:
    driver-class-name: <PAAS-TA_DB_DRIVER>                                          # (e.g. org.postgresql.Driver OR com.mysql.jdbc.Driver)
    url: jdbc:<PAAS-TA_DATABASE>://<PAAS-TA_DB_IP>:<PAAS-TA_DB_PORT>/<UAA_DB_NAME>  # (e.g. PAAS-TA_DATABASE :: postgresql OR mysql)
    username: <UAA_DB_USER_NAME>
    password: <UAA_DB_USER_PASSWORD>
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      strategy: org.hibernate.dialect.MySQL5Dialect
  generate-ddl: false

mail:
  smtp:
    host: <MAIL_SMTP_HOST>
    port: <MAIL_SMTP_PORT>
    username: <MAIL_SMTP_USERNAME>
    password: <MAIL_SMTP_PASSWORD>
    useremail: <MAIL_SMTP_USEREMAIL>
    properties:
      auth: true
      starttls:
        enable: true
        required: true
      maximumTotalQps: 90
      authUrl: http://<MAIL_SMTP_PROPERTIES_AUTHURL>
#      imgUrl: http://localhost:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png  # YOUR IMG URL
      charset: UTF-8
      subject: 'PaaS-TA User Potal 인증메일'
      createUrl: authcreate
      expiredUrl: authreset
      inviteUrl: inviteorg

paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      zuulUrl:
        cfapi: http://<PORTAL_GATEWAY_IP>:<PORTAL_GATEWAY_PORT>/portalapi
        commonapi: http://<PORTAL_GATEWAY_IP>:<PORTAL_GATEWAY_PORT>/commonapi
        storageapi: http://<PORTAL_GATEWAY_IP>:<PORTAL_GATEWAY_PORT>/storageapi
    storageapi:
      type: swift

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://<PORTAL_REGISTRATION_IP>:<PORTAL_REGISTRATION_PORT>/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

# internationalization
languageList: <PORTAL_USE_LANGUAGE>

#Hystrix Setting(current version not used)
#hystrix:
#  threadpool:
#    default:
#      # Maximum number of concurrent requests when using thread pools (Default: 10)
#      coreSize: 100
#      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
#      maxQueueSize: -1
#      # Queue size rejection threshold (Default: 5)
#      queueSizeRejectionThreshold: 5
#  command:
#    default:
#      circuitBreaker:
#        sleepWindowInMilliseconds: 60000
#        requestVolumeThreshold: 3
#      execution:
#        isolation:
#          #strategy: SEMAPHORE, no thread pool but timeout handling stops to work
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 60000
